### ISSUE TITLE
P13Sun:elaz() broken/to be implemented

### ISSUE THREAD

**Issue by dl9sec** [dl9sec/ArduinoP13#1]
The method is currently not implemented.

In the original Basic code, the calculation of azimuth and elevation for the sun seems to depend on a satellite parameter.
@brainwagon tries to use the same algorithm for azimuth/eleveation calculation as for the satellite in his implementation.

Therefore the geocentric vector to the observer (Obsvec) is subtracted from the geocentric vector to the satellite (Satvec), which results in a vector from observer to satellite (Rangevec). Then Rangevec is converted to its unit vector because for azimuth and elevation the length of Rangevec is irrelevant, just the angles must retain. Then the angles for elevation (alt) and azimuth (az) are calculated. That works fine for the satellite.

But the sun prediction method only delivers the unit vectors of the sun (celestial as SUN[], geocentrical as H[]) and not the range vector to the sun. So the calculation will fail, because the unit vector to the sun is a lot "too short".

Should find a way to convert the Sun's celestial coordinates to azimuth/elevation of an obverser...

**Comment by ulegan** [comment]
If we multiply the suns unit vector with its distance (AU), we get the suns geocentric koordinates.
Then calculate az and el the same way as with a satellite.


```C++
void P13Sun::elaz(const P13Observer &obs, double &el, double &az) {
	
    double r, u, e, n;
    Vec3 R;	// Rangevec
	
    // Rangevec = Satvec - Obsvec
    R[0] = H[0] * AU - obs.O[0] ;
    R[1] = H[1] * AU - obs.O[1] ;
    R[2] = H[2] * AU - obs.O[2] ;
	
    // Range magnitude
    r = sqrt(R[0] * R[0] + R[1] * R[1] + R[2] * R[2]);
    
    // Normalise Range vector
    R[0] /= r;
    R[1] /= r;
    R[2] /= r;
	
    // UP Component of unit range
    u = R[0] * obs.U[0] + R[1] * obs.U[1] + R[2] * obs.U[2];
    // EAST
    e = R[0] * obs.E[0] + R[1] * obs.E[1];
    //NORTH
    n = R[0] * obs.N[0] + R[1] * obs.N[1] + R[2] * obs.N[2];
	
    // Azimuth
    az = degrees(atan2(e, n));

    if (az < 0.0)
        az += 360.0;
    
    // Elevation
    el = degrees(asin(u));
}
```

**Comment by dl9sec** [comment]
Hi Uwe,

thank you very much for your implementation suggestion. Looks really simple, great stuff :-)

I comitted the implementation with https://github.com/dl9sec/ArduinoP13/commit/7feae6feef9e06aee14675587a7a47ce2f042a93

Will test it the next days...

Regards, Thorsten

**Comment by dl9sec** [comment]
Test were succesfull, P13Sun:elaz() works very well.
Thank you very much for your contribution, Uwe.

Regards, Thorsten
