### ISSUE TITLE
AioP13 doesn't show up in PlatformIO library search

### ISSUE THREAD

**Issue by SmittyHalibut** [dl9sec/ArduinoP13#3]
AioP13 shows up in the Arduino IDE library search, but it does not show up when I search for it in PlatformIO.

![image](https://user-images.githubusercontent.com/497398/146828660-a42f33db-2e1a-4810-92a4-eca808908b96.png)

My GUESS (and this is just a guess) is that you have a single-quote, apostrophe, character in `library.properties` that PlatformIO might be using to open a string.  (Github's preview of that file definitely things it's the beginning of a quote.)

Would you mind removing that apostrophe to see if PlatformIO will now work with your library directly?

https://github.com/dl9sec/AioP13/blob/master/library.properties

**Comment by SmittyHalibut** [comment]
git is hard.

Apparently github doesn't allow cherry-picked pull requests. I guess I'd have to make a separate branch, and that just seems silly for a literal one character diff.

If you accept https://github.com/dl9sec/AioP13/pull/4, then I can submit another one with this change.

**Comment by dl9sec** [comment]
Hi,
will change it today...

**Comment by dl9sec** [comment]
Hi Mark,
thank you very much for your efforts. Your pull request is merged and AioP13 1.0.2 released.
Merry Christmas to you and your family...
73, Thorsten

**Comment by dl9sec** [comment]
Does it show up now in PlatformIO?

**Comment by dl9sec** [comment]
No response, so closed...
