### ISSUE TITLE
Compiler warnings, potential bad string pointers, add dopplerOffset() 

### ISSUE THREAD

**Issue by SmittyHalibut** [dl9sec/ArduinoP13#5]
This is just an issue to go with a pull-request that I've already filed. :-)

1. There were several compiler warnings when building this on PlatformIO. They were relatively easy to clean up.
1. The code holds pointers to strings owned by other code. The problem is, if those strings go out of scope, we are left with an invalid pointer. It's a bug to dereference a pointer to an object that's no longer in scope.  Those strings should be copied into the object, so it has its own copy.
1. I'd like to get access to just the doppler offset, not the final resultant frequency.  But everything I need to get that is `private`.

**Comment by SmittyHalibut** [comment]
https://github.com/dl9sec/AioP13/pull/4

**Comment by dl9sec** [comment]
Hi Mark,
thank you very much for your efforts. Your pull request is merged and AioP13 1.0.2 released.
Merry Christmas to you and your family...
73, Thorsten
