### ISSUE TITLE
Wrong results in ISS calculations

### ISSUE THREAD

**Issue by iu2frl** [dl9sec/ArduinoP13#7]
Hi,
I am using this library to calculate position of ISS in my code but something is not working properly, here is the code:

```cpp
#define WIFISSID "SSID"
#define WIFIPASS "PASS"
const double sta_latitude = 10.9838;
const double sta_longitude = 45.4315;
const double sta_altitude = 20.0;

#include <AioP13.h>
#include <WiFi.h>
#include <NTPClient.h>
#include <WiFiUdp.h>
#include <HTTPClient.h>
#include <WiFiClientSecureBearSSL.h>

WiFiUDP ntpUDP;
NTPClient timeClient(ntpUDP);

double sat_azimuth;
double sat_elevation;

char tle_name[] = "ISS (ZARYA)";
char tle_line1[] = "1 25544U 98067A   23359.76507144  .00020249  00000-0  36546-3 0  9990";  //Line one from the TLE data
char tle_line2[] = "2 25544  51.6426  99.5712 0003107 312.8493 147.5918 15.49716429431506";  //Line two from the TLE data

const ulong updateTime = 1 * 1000;
ulong lastSatUpdate = 0;

bool IsWifiConnected() {
  return WiFi.status() == WL_CONNECTED;
}

void WifiSetup(const char *ssid, const char *pass) {
  WiFi.mode(WIFI_STA);     // Put wifi into station mode
  WiFi.begin(ssid, pass);  // start connecting to wifi
  Serial.print("Connecting...");
  while (!IsWifiConnected()) {
    delay(500);
    Serial.print(".");
    delay(500);
  }
  // connection established
  Serial.println("");
  Serial.print("WiFi connection established with ");
  Serial.println(WiFi.SSID());
  // print IP Address
  Serial.print("Assinged IP: ");
  Serial.println(WiFi.localIP());
}

void UpdateSatellitePos() {
  // Init satellite object
  P13Satellite MySAT(tle_name, tle_line1, tle_line2);
  time_t epochTime = timeClient.getEpochTime();
  struct tm *ptm = gmtime((time_t *)&epochTime);
  P13DateTime MyTime(ptm->tm_year + 1900,
                     ptm->tm_mon + 1,
                     ptm->tm_mday,
                     ptm->tm_hour,
                     ptm->tm_min,
                     ptm->tm_sec);  // Set start time for the prediction
  // Predict for specific time
  MySAT.predict(MyTime);
  // Get the rectangular coordinates
  //MySAT.latlon(dSatLAT, dSatLON);
  // Get the QTH
  P13Observer MyQTH("Ground station", sta_latitude, sta_longitude, sta_altitude);
  // Get azimut and elevation for MyQTH
  MySAT.elaz(MyQTH, sat_elevation, sat_azimuth);
}

void PrintConsole() {
  Serial.println("-------------------------------------------");
  // Get time from NTP
  Serial.print("UTC Time: ");
  Serial.println(timeClient.getFormattedTime());
  // Print some data
  Serial.println("Station coordinates: " + String(sta_latitude) + ", " + String(sta_longitude));
  Serial.println(String(tle_name) + " Azimuth: " + String(sat_azimuth) + ", Elevation: " + String(sat_elevation));
}

void setup() {
  // Init serial port
  Serial.begin(115200);
  Serial.println();
  // Connect to WiFi
  WifiSetup(WIFISSID, WIFIPASS);
  // Start the web server
  server.begin();
  // Start NTP client
  timeClient.begin();
}

void loop() {
  // Update time every X miliseconds
  ulong curTime = millis();
  if (curTime - lastSatUpdate >= updateTime) {
    timeClient.update();
    // Update satellite position
    UpdateSatellitePos();
    // Print data to console
    PrintConsole();
    // Prepare for next update
    lastSatUpdate = curTime;
  }
  // Manage OTA Updates
  ArduinoOTA.handle();
}

```

Using the same TLEs and ground station coords in Orbitron i get:
- Azimuth: 64.3
- Elevation: -2.6

Code shows:
- Azimuth: 239.33
- Elevation: -65.83

**Comment by dl9sec** [comment]
Hi,

it seems, that the TLE data you used is out of date.
Please update the TLE from
https://celestrak.org/NORAD/elements/gp.php?GROUP=stations&FORMAT=tle

Regards, Thorsten

**Comment by iu2frl** [comment]
I double checked, but still results are wrong

![image](https://github.com/dl9sec/AioP13/assets/61653175/f4b4d7f9-6711-4425-80cd-f699d7c08c7c)

**Comment by iu2frl** [comment]
I checked the code once again, but still different output with same TLEs

![image](https://github.com/dl9sec/AioP13/assets/61653175/5861cb03-84dc-4d46-abdb-d6fb6f90412c)

**Comment by dl9sec** [comment]
I would say you mixed up lat and lon if you are in Verona near Via Cità di Nimes.
Please set:
const double sta_latitude = 45.4315;
const double sta_longitude = 10.9838;

Regards, Thorsten

**Comment by iu2frl** [comment]
As you can see in the screenshots the difference in azimuth is over 100 degrees and the elevation is over 10 degrees (which gets progressively worse when the satellite gets further). Even after changing the home position by the a couple decimals, the results are still wrong

**Comment by iu2frl** [comment]
Same coordinates, same TLE, same time

![image](https://github.com/dl9sec/AioP13/assets/61653175/276c0590-500c-4d4a-ac7d-ab6bbb6a70a8)

**Comment by dl9sec** [comment]
To compare AZ/EL you must compare exactly at the same time. ISS is in a low orbit an passes very quick, so 10s difference in time can make a big difference in AZ. As you can see EL is ok...

**Comment by iu2frl** [comment]
The time is not the issue, if I jog orbitron to the sime time, the calculations are still wrong. The elevation being right it was just a casualty, it's usually completely off

**Comment by iu2frl** [comment]
I'm starting to go down a different path, if I set a double value with 4 decimal places, it's being printed with only two decimal digits, I hope is not a limitation of the Pi Pico W that I'm using

**Comment by iu2frl** [comment]
Exactly same time, same TLE, same coords, completely wrong both altitude and azimuth

![image](https://github.com/dl9sec/AioP13/assets/61653175/7e8f84d9-888b-4c85-bccf-a893ce07fdbc)

**Comment by iu2frl** [comment]
Decimal places were not the issue, I am doing some testing and it's just the Serial.print to use two decimal places, i run some test code and the actual value has all the decimal digits

**Comment by iu2frl** [comment]
Interestingly enough, the calculated ground coordinates are just perfect (compared with https://www.astroviewer.net/iss/en/)

I double checked ground station coordinates and they are good, also getting c_dLA and c_dLO from the P13Observer object returns the right position in radians, time is good... I'm so confused...

![image](https://github.com/dl9sec/AioP13/assets/61653175/0db54f82-9ba6-4564-8282-1c53ae5d5799)

**Comment by iu2frl** [comment]
Looks like i got it, for some unclear reason the time was not working fine!
